### ISSUE TITLE
OSX 上有如下错误信息

### ISSUE THREAD

**Issue by zhangshenhua** [ma6174/vim#115]
[zhangshenhua@mac104 ~/vim]$ vim
Error detected while processing /Users/zhangshenhua/.vim/plugin/blog.vim:
line  835:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/zhangshenhua/anaconda/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/Users/zhangshenhua/anaconda/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/Users/zhangshenhua/anaconda/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Users/zhangshenhua/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/zhangshenhua/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/zhangshenhua/anaconda/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/zhangshenhua/anaconda/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/zhangshenhua/anaconda/lib/python2.7/lib-dynload/_io.so
Press ENTER or type command to continue
[zhangshenhua@mac104 ~/vim]$

**Comment by glassysky** [comment]
+1

**Comment by zsky** [comment]
应该是 python 版本的问题
我电脑上执行 brew unlink python 就好了
