### ISSUE TITLE
Error detected while processing client.vim

### ISSUE THREAD

**Issue by chenai** [ma6174/vim#57]
I used wget command to download and install your vim configuration file on a max OSX 10.9 system, and when I finished the install and run vim, there is an error like this:

Error detected while processing /Users/sam/.vim/plugin/client.vim:
line  314:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Library/Python/2.7/site-packages/Twisted-14.0.2-py2.7-macosx-10.9-intel.egg/twisted/__init__.py", line 53, in <module>
    _checkRequirements()
  File "/Library/Python/2.7/site-packages/Twisted-14.0.2-py2.7-macosx-10.9-intel.egg/twisted/__init__.py", line 37, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.

How to fix that ?

**Comment by chenai** [comment]
I used "pip install twisted" and still not working

**Comment by ma6174** [comment]
maybe `client.vim` not very useful, I have deleted from  repository.

if you use this plugin, try this to install twisted: http://stackoverflow.com/questions/11010412/importerror-no-module-named-zope-interface
