### ISSUE TITLE
Error detected while processing /private/var/.home/admin/.vim/plugin/blog.vim

### ISSUE THREAD

**Issue by dendisuhubdy** [ma6174/vim#85]
Error detected while processing /private/var/.home/admin/.vim/plugin/blog.vim:
line  835:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

**Comment by normanyahq** [comment]
http://stackoverflow.com/questions/25276329/cant-load-python-modules-installed-via-pip-from-site-packages-directory

原因是MAC自带的python跟你自己安装的python混起来了。

解决方法
1、将~/.vim/plugin/blog.vim删除或改为非.vim的后缀名
2、将export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages加到shell配置文件，默认应该是bash的  ~/.bash_profile，zsh是~/.zshrc
